Traceback (most recent call last):
  File "User_Data/sach/codePy.py", line 40, in <module>
    print(2/0)
ZeroDivisionError: division by zero
